### ISSUE TITLE
fails to build with aeson-2.2?

### ISSUE THREAD

**Issue by juhp** [brandonchinn178/aeson-schemas#93]
For Stackage Nightly
```
       /home/curators/work/unpack-dir/unpacked/aeson-schemas-1.4.2.0-fc3271e9dbf1b79552f89b6538d5581ed110a857d0ed3db972877bd8e6f2638
2/bench/Utils/DeepSeq.hs:16:10: error: [GHC-39999]                                                                                  
           • No instance for ‘NFData BndrVis’                                                                                       
               arising from a use of ‘Control.DeepSeq.$dmrnf’                                                                       
           • In the expression: Control.DeepSeq.$dmrnf @(Dec)                                                                       
             In an equation for ‘rnf’: rnf = Control.DeepSeq.$dmrnf @(Dec)                                                          
             In the instance declaration for ‘NFData Dec’                                                                           
          |                                                                                                                         
       16 | instance NFData Dec                                                                                                     
          |          ^^^^^^^^^^                                                                                                     
                                                                                                                                    
       /home/curators/work/unpack-dir/unpacked/aeson-schemas-1.4.2.0-fc3271e9dbf1b79552f89b6538d5581ed110a857d0ed3db972877bd8e6f2638
2/bench/Utils/DeepSeq.hs:51:10: error: [GHC-39999]                                                                                  
           • No instance for ‘NFData BndrVis’                                                                                       
               arising from a use of ‘Control.DeepSeq.$dmrnf’                                                                       
           • In the expression: Control.DeepSeq.$dmrnf @(TypeFamilyHead)                                                            
             In an equation for ‘rnf’:                                                                                              
                 rnf = Control.DeepSeq.$dmrnf @(TypeFamilyHead)                                                                     
             In the instance declaration for ‘NFData TypeFamilyHead’                                                                
          |                                                                                                                         
       51 | instance NFData TypeFamilyHead                                                                                          
          |          ^^^^^^^^^^^^^^^^^^^^^                                                                                          
 ```

**Comment by brandonchinn178** [comment]
Fixed by #94
